#!/usr/bin/env bun
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";

const ROOT = join(dirname(new URL(import.meta.url).pathname), "..");
const GENERATED_MODULE = join(ROOT, "src", "generated", "embedded-assets.ts");

export interface PlatformTarget {
  /** Package suffix after `easyresearch-`, e.g. `linux-x64`. */
  name: string;
  /** Bun compile target, e.g. `bun-linux-x64`. */
  target: string;
  os: string[];
  cpu: string[];
}

export const TARGETS: PlatformTarget[] = [
  { name: "linux-x64", target: "bun-linux-x64", os: ["linux"], cpu: ["x64"] },
  { name: "linux-x64-baseline", target: "bun-linux-x64-baseline", os: ["linux"], cpu: ["x64"] },
  { name: "linux-x64-musl", target: "bun-linux-x64-musl", os: ["linux"], cpu: ["x64"] },
  { name: "linux-arm64", target: "bun-linux-arm64", os: ["linux"], cpu: ["arm64"] },
  { name: "darwin-x64", target: "bun-darwin-x64", os: ["darwin"], cpu: ["x64"] },
  { name: "darwin-x64-baseline", target: "bun-darwin-x64-baseline", os: ["darwin"], cpu: ["x64"] },
  { name: "darwin-arm64", target: "bun-darwin-arm64", os: ["darwin"], cpu: ["arm64"] },
  { name: "windows-x64", target: "bun-windows-x64", os: ["win32"], cpu: ["x64"] },
  { name: "windows-x64-baseline", target: "bun-windows-x64-baseline", os: ["win32"], cpu: ["x64"] },
  { name: "windows-arm64", target: "bun-windows-arm64", os: ["win32"], cpu: ["arm64"] },
];

export function releaseDir(): string {
  return join(ROOT, "release");
}

export function platformPackageDir(targetName: string): string {
  return join(releaseDir(), `easyresearch-${targetName}`);
}

export function platformBinaryName(target: PlatformTarget): string {
  return target.os[0] === "win32" ? "easyresearch.exe" : "easyresearch";
}

export function repoPackageVersion(): string {
  const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as { version: string };
  return pkg.version;
}

function collectFiles(root: string, prefix: string): string[] {
  const files: string[] = [];
  const visit = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const abs = join(dir, entry.name);
      if (entry.isDirectory()) visit(abs);
      else if (entry.isFile()) files.push(prefix + abs.slice(root.length + 1));
    }
  };
  if (existsSync(root)) visit(root);
  return files.sort();
}

/**
 * Enumerate every file shipped inside the standalone binary: web UI bundle,
 * bundled agents/skills, and pi's runtime assets (package.json, README, themes).
 */
export function collectEmbeddedAssets(): string[] {
  const piPkg = join(ROOT, "node_modules", "@earendil-works", "pi-coding-agent");
  return [
    ...collectFiles(join(ROOT, "src", "webui", "dist"), "webui/dist/"),
    ...collectFiles(join(ROOT, "src", "agents"), "agents/").filter((rel) => rel.endsWith(".md")),
    ...collectFiles(join(ROOT, "src", "skills"), "skills/"),
    ...["package.json", "README.md"].map((file) => `pi/${file}`),
    ...collectFiles(join(piPkg, "dist", "modes", "interactive", "theme"), "pi/theme/").filter((rel) =>
      rel.endsWith(".json"),
    ),
  ];
}

/**
 * Regenerate src/generated/embedded-assets.ts. The module uses `with { type:
 * "file" }` imports so the bundler embeds each asset into compiled binaries;
 * running from source the same imports resolve to real disk paths. A
 * `@ts-nocheck` header keeps tsc happy about non-TS module imports.
 */
export function generateEmbeddedAssetsModule(): string[] {
  const rels = collectEmbeddedAssets();
  const version = repoPackageVersion();
  const lines: string[] = [
    "// @ts-nocheck",
    "// Generated by scripts/build.ts — do not edit.",
    "// Embedded file map keyed by repo-relative path; empty in fresh checkouts (dev falls back to disk).",
  ];
  rels.forEach((rel, index) => {
    lines.push(`import _e${index} from ${JSON.stringify(moduleRelative(rel))} with { type: "file" };`);
  });
  lines.push("");
  lines.push("export const embeddedFiles: Record<string, string> = {");
  rels.forEach((rel, index) => {
    lines.push(`  ${JSON.stringify(rel)}: _e${index},`);
  });
  lines.push("};");
  lines.push("");
  lines.push(`export const embeddedVersion = ${JSON.stringify(version)};`);
  lines.push("");
  const content = lines.join("\n");
  if (readFileSync(GENERATED_MODULE, "utf8") !== content) writeFileSync(GENERATED_MODULE, content);
  return rels;
}

function moduleRelative(rel: string): string {
  if (rel.startsWith("pi/theme/")) {
    return `../../node_modules/@earendil-works/pi-coding-agent/dist/modes/interactive/theme/${rel.slice(
      "pi/theme/".length,
    )}`;
  }
  if (rel.startsWith("pi/")) {
    return `../../node_modules/@earendil-works/pi-coding-agent/${rel.slice("pi/".length)}`;
  }
  return `../${rel}`;
}

export async function buildWebUi(): Promise<void> {
  const { build } = await import("vite");
  await build({ configFile: join(ROOT, "src", "webui", "vite.config.ts"), logLevel: "info" });
}

export async function compileTarget(target: PlatformTarget): Promise<string> {
  const pkgDir = platformPackageDir(target.name);
  const binDir = join(pkgDir, "bin");
  mkdirSync(binDir, { recursive: true });
  const outfile = join(binDir, platformBinaryName(target));
  const result = await Bun.build({
    entrypoints: [join(ROOT, "src", "cli", "index.ts")],
    compile: { target: target.target as Bun.Build.CompileTarget, outfile },
    minify: true,
  });
  if (!result.success) {
    throw new Error(`compile failed for ${target.name}: ${JSON.stringify(result.logs)}`);
  }
  return outfile;
}

export async function buildTargets(only?: string): Promise<PlatformTarget[]> {
  await buildWebUi();
  generateEmbeddedAssetsModule();
  const targets = TARGETS.filter((t) => only === undefined || t.name === only);
  if (targets.length === 0) throw new Error(`unknown target: ${only}`);
  for (const target of targets) {
    console.log(`[build] compiling ${target.name} (${target.target})…`);
    const outfile = await compileTarget(target);
    const size = statSync(outfile).size;
    console.log(`[build] ${target.name} -> ${outfile} (${(size / 1024 / 1024).toFixed(1)} MiB)`);
  }
  return targets;
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const onlyIndex = args.indexOf("--only");
  const only = onlyIndex >= 0 ? args[onlyIndex + 1] : undefined;
  await buildTargets(only);
}
